"""Init Reddit tables

Revision ID: e128fb481f2f
Revises: 
Create Date: 2026-07-06 21:05:49.141613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e128fb481f2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_keywords_keyword'), 'reddit_keywords', ['keyword'], unique=True)
    op.create_table('reddit_subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_subreddits_name'), 'reddit_subreddits', ['name'], unique=True)
    op.create_table('reddit_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('permalink', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('is_mod', sa.Boolean(), nullable=False),
    sa.Column('distinguished', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('created_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('preview_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('link_flair', sa.String(), nullable=True),
    sa.Column('post_flair', sa.String(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'FILTERED', 'QUEUED', 'PROCESSING', 'PROCESSED', 'NOTIFIED', 'FAILED', 'DUPLICATE', name='poststatus'), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subreddit_id'], ['reddit_subreddits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_posts_created_utc'), 'reddit_posts', ['created_utc'], unique=False)
    op.create_index(op.f('ix_reddit_posts_status'), 'reddit_posts', ['status'], unique=False)
    op.create_table('reddit_ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['reddit_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('reddit_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['reddit_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reddit_notifications')
    op.drop_table('reddit_ai_analysis')
    op.drop_index(op.f('ix_reddit_posts_status'), table_name='reddit_posts')
    op.drop_index(op.f('ix_reddit_posts_created_utc'), table_name='reddit_posts')
    op.drop_table('reddit_posts')
    op.drop_index(op.f('ix_reddit_subreddits_name'), table_name='reddit_subreddits')
    op.drop_table('reddit_subreddits')
    op.drop_index(op.f('ix_reddit_keywords_keyword'), table_name='reddit_keywords')
    op.drop_table('reddit_keywords')
    # ### end Alembic commands ###
